repos:
-   repo: https://github.com/NTT-DATA-Cloud-Transformation/central-repo-git-hooks.git
    rev: master
    hooks:
    -   id: check-readme
    -   id: terraform-fmt
    -   id: packer-validate
    -   id: cfn-lint
    -   id: flake8-lint
    -   id: security-check
    -   id: check-prtemplate
